version: '3.8'

services:
  bot:
    build: .
    container_name: universe-telegram-bot
    # restart: always
    volumes:
      - ./data:/app/data 
      - ./config:/app/config
    env_file:
      - ./config/.env
      